spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/classroom
    username: classroom
    password: classroom
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  threads:
    virtual:
      enabled: true

